version: 0.2

phases:
  install:
    commands:
      - npm install -g npm@6
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 sync ./dist $S3_BUCKET